version: "3.4"
services:
  vite_docker:
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - "8080:8080"
    working_dir: /var/www/app
    volumes:
      - type: bind
        source: ./
        target: /var/www/app
    tty: true
